spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

service:
  putsreq-echo:
    URL: ${service.putsreq-echo.URL}
    Authorization: ${service.putsreq-echo.Authorization}